// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlvZycIOFwvDhck6Yiuvn0VKXmZZEFVog',
    appId: '1:944891158319:web:3c0a7c49388e7eddf88bda',
    messagingSenderId: '944891158319',
    projectId: 'whatsappclone-26c2f',
    authDomain: 'whatsappclone-26c2f.firebaseapp.com',
    storageBucket: 'whatsappclone-26c2f.firebasestorage.app',
    measurementId: 'G-TTL437TS0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-_wQbL5UHs8acis7_NFi6FwggKFd2O-8',
    appId: '1:944891158319:android:4b961e1687260840f88bda',
    messagingSenderId: '944891158319',
    projectId: 'whatsappclone-26c2f',
    storageBucket: 'whatsappclone-26c2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeAOuFyqgVv2wMsHU4W9NMc4qr-hA82wo',
    appId: '1:944891158319:ios:2b947b26afee41d5f88bda',
    messagingSenderId: '944891158319',
    projectId: 'whatsappclone-26c2f',
    storageBucket: 'whatsappclone-26c2f.firebasestorage.app',
    iosBundleId: 'com.example.whatsappclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeAOuFyqgVv2wMsHU4W9NMc4qr-hA82wo',
    appId: '1:944891158319:ios:2b947b26afee41d5f88bda',
    messagingSenderId: '944891158319',
    projectId: 'whatsappclone-26c2f',
    storageBucket: 'whatsappclone-26c2f.firebasestorage.app',
    iosBundleId: 'com.example.whatsappclone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlvZycIOFwvDhck6Yiuvn0VKXmZZEFVog',
    appId: '1:944891158319:web:fddf7981b46cc6b8f88bda',
    messagingSenderId: '944891158319',
    projectId: 'whatsappclone-26c2f',
    authDomain: 'whatsappclone-26c2f.firebaseapp.com',
    storageBucket: 'whatsappclone-26c2f.firebasestorage.app',
    measurementId: 'G-S4DVTVLHR7',
  );
}
