
 import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:whatsappclone/core/MyColors.dart';

import 'appTheme.dart';

class icons {
  static Icon emailIcon = Icon(Icons.email);
  static Icon passIcon = Icon(Icons.password);
  static Icon name = Icon(Icons.person);
  static Icon logout = Icon(Icons.logout,color: myColors.delete,);
  static Icon image = Icon(Icons.image);
  static Icon whiteImage = Icon(CupertinoIcons.photo,);
  static Icon send = Icon(Icons.send,color: myColors.myMessage);
  static Icon arrow = Icon(Icons.arrow_back);
  static Icon add = Icon(Icons.add);
  static Icon visibility = Icon(Icons.visibility);
  static Icon visibility_off = Icon(Icons.visibility_off);
  static Icon contacts = Icon(CupertinoIcons.person);
  static Icon chats = Icon(Icons.chat);
  static Icon settings = Icon(Icons.settings);
  static Icon person = Icon(Icons.person, size: 30,);
  static Icon arrowForward = Icon(Icons.arrow_forward_ios);
  static Icon remove = Icon(Icons.remove_circle);
  static Icon tick = Icon(Icons.check, color: myColors.tick, size: 40);
  static Icon colors = Icon(Icons.color_lens_outlined);
  static Icon deleteIcon = Icon(CupertinoIcons.delete, color: myColors.delete);
  static Icon copy = Icon(Icons.copy,color: myTheme.appTheme == true ? Colors.white : Colors.black,);
  static Icon wcopy = Icon(Icons.copy, color: Colors.white,);
  static Icon edit = Icon(CupertinoIcons.pencil, color: myColors.tick, size: 27,);
  static Icon camera = Icon(CupertinoIcons.camera,);
  static Icon cancel = Icon(Icons.cancel_outlined,);
  static Icon dCam = Icon(Icons.camera_alt_outlined);
  static Icon file = Icon(Icons.file_copy_outlined);
  static Icon star = Icon(Icons.star_border_outlined, color: myColors.labelClr,);
  static Icon noStar = Icon(Icons.stars, color: myColors.starColor, size: 90,);
  static Icon wStar = Icon(Icons.star, color: Colors.white,size: 18,);
  static Icon slash = Icon(CupertinoIcons.star_slash_fill, size: 30,);
  static Icon stary = Icon(CupertinoIcons.star, size: 30,color: Colors.black,);
  static Icon amberStar = Icon(Icons.star, color: myColors.amberStar);
  static Icon noImages = Icon(CupertinoIcons.photo, size: 50,);
  static Icon supportedImage = Icon(Icons.image_not_supported, size: 50, color: Colors.grey);
  static Icon share =Icon(CupertinoIcons.share, color: Colors.black,);
  static Icon close = Icon(Icons.close);
  static Icon Wclose = Icon(Icons.close, color: Colors.white,);
  static Icon reply = Icon(Icons.reply, color: myColors.labelClr,);
  static Icon Wphoto = Icon(CupertinoIcons.photo, size: 20,color: Colors.white,);
  static Icon selectIcon = Icon(Icons.check_circle_outline, color: myColors.labelClr);
  static Icon search = Icon(Icons.search);
  static Icon instagram = Icon(FontAwesomeIcons.instagram);
  static Icon messageRead = Icon(Icons.done_all, color: myColors.readColor);
  static Icon sent = Icon(Icons.check, color: myColors.sent,);
  static Icon unread =Icon(Icons.mark_chat_unread, size: 23, color: Colors.white,);
  static Icon options = Icon(Icons.more_horiz_outlined, size: 27,);
  static Icon fave = Icon(Icons.favorite_border);
  static Icon mute = Icon(Icons.volume_off_outlined);
  static Icon info = Icon(Icons.info_outline);
}