
 import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:whatsappclone/core/MyColors.dart';

import 'appTheme.dart';

class icons {
  static Icon emailIcon = const Icon(Icons.email);
  static Icon passIcon = Icon(Icons.password);
  static Icon name = const Icon(Icons.person);
  static Icon logout = Icon(Icons.logout,color: MyColors.delete,);
  static Icon image = const Icon(Icons.image);
  static Icon whiteImage = const Icon(CupertinoIcons.photo,);
  static Icon send = Icon(Icons.send,color: MyColors.myMessage);
  static Icon arrow = const Icon(Icons.arrow_back);
  static Icon add = const Icon(Icons.add);
  static Icon visibility = const Icon(Icons.visibility);
  static Icon visibility_off = const Icon(Icons.visibility_off);
  static Icon contacts = const Icon(CupertinoIcons.person);
  static Icon chats = const Icon(Icons.chat);
  static Icon settings = const Icon(Icons.settings);
  static Icon person = const Icon(Icons.person, size: 30,);
  static Icon arrowForward = const Icon(Icons.arrow_forward_ios);
  static Icon remove = const Icon(Icons.remove_circle);
  static Icon tick = Icon(Icons.check, color: MyColors.tick, size: 40);
  static Icon colors = const Icon(Icons.color_lens_outlined);
  static Icon deleteIcon = Icon(CupertinoIcons.delete, color: MyColors.delete);
  static Icon copy = Icon(Icons.copy,color: MyTheme.appTheme == true ? Colors.white : Colors.black,);
  static Icon wcopy = const Icon(Icons.copy, color: Colors.white,);
  static Icon edit = Icon(CupertinoIcons.pencil, color: MyColors.tick, size: 27,);
  static Icon camera = const Icon(CupertinoIcons.camera,);
  static Icon cancel = const Icon(Icons.cancel_outlined,);
  static Icon dCam = const Icon(Icons.camera_alt_outlined);
  static Icon file = const Icon(Icons.file_copy_outlined);
  static Icon star = Icon(Icons.star_border_outlined, color: MyColors.labelClr,);
  static Icon noStar = Icon(Icons.stars, color: MyColors.starColor, size: 90,);
  static Icon wStar = const Icon(Icons.star, color: Colors.white,size: 18,);
  static Icon slash = const Icon(CupertinoIcons.star_slash_fill, size: 30,);
  static Icon stary = const Icon(CupertinoIcons.star, size: 30,color: Colors.black,);
  static Icon amberStar = Icon(Icons.star, color: MyColors.amberStar);
  static Icon noImages = const Icon(CupertinoIcons.photo, size: 50,);
  static Icon supportedImage = const Icon(Icons.image_not_supported, size: 50, color: Colors.grey);
  static Icon share = const Icon(CupertinoIcons.share, color: Colors.black,);
  static Icon close = const Icon(Icons.close);
  static Icon Wclose = const Icon(Icons.close, color: Colors.white,);
  static Icon reply = Icon(Icons.reply, color: MyColors.labelClr,);
  static Icon Wphoto = const Icon(CupertinoIcons.photo, size: 20,color: Colors.white,);
  static Icon selectIcon = Icon(Icons.check_circle_outline, color: MyColors.labelClr);
  static Icon search = const  Icon(Icons.search);
  static Icon instagram = const Icon(FontAwesomeIcons.instagram);
  static Icon messageRead = Icon(Icons.done_all, color: MyColors.readColor);
  static Icon sent = Icon(Icons.check, color: MyColors.sent,);
  static Icon unread = const Icon(Icons.mark_chat_unread, size: 23, color: Colors.white,);
  static Icon options =  const Icon(Icons.more_horiz_outlined, size: 27,);
  static Icon fave = const  Icon(Icons.favorite_border);
  static Icon mute = const Icon(Icons.volume_off_outlined);
  static Icon info = const Icon(Icons.info_outline);
  static Icon vOff =  const Icon(Icons.volume_off, size: 18, color: Colors.black);
  static Icon volumeUp = const Icon(Icons.volume_up);
  static Icon myFavourite = const Icon(Icons.favorite);
}